version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kanastra-api
    volumes:
      - ./:/var/www
      - ./.setup/php/php-fpm-www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      - kanastra

  nginx:
    image: nginx:alpine
    container_name: kanastra-nginx
    volumes:
      - ./:/var/www:ro
      - ./.setup/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./.setup/nginx/default-compose.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    networks:
      - kanastra
    depends_on:
      - app

  mysql:
    image: mysql:5.7.29
    container_name: kanastra-db
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./.docker/mysql:/var/lib/mysql
      - ./.setup/mysql/mysql-custom.cnf:/etc/mysql/conf.d/mysql-custom.cnf
    ports:
      - ${DB_PORT}:3306
    expose:
      - 3306
    networks:
      - kanastra

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8877:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - kanastra

networks:
  kanastra:
    driver: bridge
